### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by VictorDDT** [ZiiCEagle/Slider#1]
Hi. Thanks for the good slider!

Is it possible to set slider position from an external code?
Is it possible to have animation (smooth sliding between current and given position)?

**Comment by guillaumebriday** [comment]
Hey, I didn't even remember that this project exists 😂 

But no it's not possible possible at this time you just can change the default width, unfortunately I have no time to do this, feel free to open a PR, I will take a look.

Thanks
